name: "Make Yoink Installers"
on: 
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  what-do-i-name-this:
    name: "Make installers"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Make regular installer
        run: |
          cd installer
          npm install
          node make -o ../installer-regular.js
          cd ..
      - name: Upload regular installer
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: installer-regular.js
          allow_override: true
          gzip: false
      - name: Clone wizard generator
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        with:
          owner: 'Ponali'
          repository: 'w93-wizard-generator'
      - name: Make Source installer
        run: |
          cd w93-wizard-generator
          npm install
          node make .. -o ../installer-source.js
          cd ..
      - name: Upload source installer
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: installer-source.js
          allow_override: true
          gzip: false
